const {chromium}=require('@playwright/test');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,timeout:20000});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(process.env.TEST_URL,{waitUntil:'networkidle'});
  await page.waitForFunction(()=>document.querySelector('#hero').naturalWidth>0);
  assert.equal(await page.locator('#decision-title').innerText(),'Not scored yet');
  assert.equal(await page.locator('#agree').isDisabled(),true);
  const photo=await page.locator('.photo-stage').boundingBox();
  assert.ok(photo.width>600&&photo.height>400);
  const actions=await page.locator('footer').boundingBox();
  assert.ok(actions.y+actions.height<=1001);
  await page.locator('#score-button').click();
  await page.locator('#score-dialog').waitFor({state:'visible'});
  assert.equal(await page.locator('#run-score').isDisabled(),true);
  await page.locator('#paid-check').check();
  await page.locator('#run-score').click();
  await page.waitForFunction(()=>document.querySelector('#decision-title').textContent==='Can’t tell');
  await page.waitForFunction(()=>!document.querySelector('#agree').disabled);
  assert.match(await page.locator('#progress').innerText(),/1 ready/);
  assert.match(await page.locator('#gpt-score').innerText(),/0.71/);
  assert.equal(await page.locator('#agree').isEnabled(),true);
  await page.locator('#correct').click();
  await page.locator('#name-dialog').waitFor({state:'visible'});
  await page.locator('#name-input').fill('Isolated reviewer');
  await page.locator('#name-form button.primary').click();
  await page.locator('#answer-dialog').waitFor({state:'visible'});
  await page.locator('#answer-fit').selectOption('unsure');
  await page.locator('#answer-reason').fill('Missing bathroom evidence');
  await page.locator('#answer-form button.primary').click();
  await page.waitForFunction(()=>document.querySelector('#saved-answer').textContent.includes('Can’t tell'));
  assert.match(await page.locator('#progress').innerText(),/1 reviewed/);
  await page.locator('#edit-photo').click();
  await page.locator('#photo-dialog').waitFor({state:'visible'});
  await page.locator('#photo-edit-room').selectOption('bathroom');
  assert.equal(await page.locator('#photo-preference').inputValue(),'');
  await page.locator('#photo-edit-context').selectOption('shared_amenity');
  assert.equal(await page.locator('#photo-preference').isDisabled(),true);
  assert.ok(await page.locator('#photo-features select').evaluateAll(nodes=>nodes.every(n=>n.value===''&&n.disabled)));
  await page.locator('[data-close="photo-dialog"]').click();
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
  await page.locator('#queue-toggle').click();
  assert.equal(await page.locator('.queue').isVisible(),true);
  await page.locator('.queue-item').first().click();
  await page.locator('.queue').waitFor({state:'hidden'});
  assert.equal(await page.locator('.queue').isVisible(),false);
  assert.deepEqual(errors,[]);
  console.log('PASS: large image-first reviewer; unscored state; explicit single paid mock; auto-refresh; corrected property save; photo controls; mobile queue; zero live mutations.');
 }finally{await browser.close();}
})().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1)});
