const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
class Element{constructor(tag='div'){this.tag=tag;this.children=[];this.value='';this.textContent='';this.hidden=false;this.disabled=false;this.classList={toggle(){}};this.dataset={}}append(...x){this.children.push(...x)}replaceChildren(...x){this.children=x}setAttribute(){}removeAttribute(){}contains(){return true}}
const html=fs.readFileSync('training_studio.html','utf8'),els={};for(const m of html.matchAll(/id="([^"]+)"/g))els[m[1]]=new Element();
const script=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].at(-1)[1].replace('guard(boot)();','');
const calls=[],saved=[],schema=JSON.parse(fs.readFileSync('contracts/actvision-v2.schema.json','utf8'));
const detail={label_evidence_id:'a'.repeat(64),property:{id:'sample',address:'Example',mls_remarks:'Original finishes.',metadata:{},review:{revision:0}},images:[],historical_source:{blocked:false,timing_verified:true}};
const draft={label_evidence_id:detail.label_evidence_id,physical_condition:'UNKNOWN',modernization_state:'ORIGINAL',acquisition_fit:'TARGET',reason:'Original finishes; repair needs unknown.',input_sha256:'input',proposal_id:'proposal',text_signals:[{signal:'original_condition',state:'PRESENT',probability:null,snippet:'Original finishes',start:0,end:17},{signal:'needs_tlc',state:'UNKNOWN',probability:null,snippet:null,start:null,end:null}]};
let reject=false;
const context={console,structuredClone,document:{getElementById:id=>els[id],createElement:t=>new Element(t),createTextNode:text=>({textContent:text}),querySelectorAll:()=>[],addEventListener(){}},window:{location:{hash:'',assign(){}},confirm:()=>true,getSelection:()=>null,addEventListener(){}},fetch:async(path,opts)=>{calls.push({path,method:opts.method});let data={};if(path.includes('capabilities'))data={token:'csrf',cloud:true,actor:{id:'reviewer',role:'reviewer'},taxonomy:{physical_condition:schema.$defs.condition.enum,modernization:schema.$defs.modernization.enum,acquisition_fit:schema.$defs.acquisition_fit.enum,text_signals:schema.$defs.text_signal.enum}};else if(path.includes('review-queue'))data={items:[{id:'sample'}],total:1,counts:{}};else if(path.includes('/property?'))data=structuredClone(detail);else if(path.includes('label/proposal'))data={request:{status:'completed'},proposal:structuredClone(draft)};else if(path==='/api/studio/v2/label'){if(reject)data={error:'Evidence changed'};else{saved.push(JSON.parse(opts.body));data={revision:1}}}return{ok:!reject,status:reject?409:200,headers:{get:()=> 'application/json'},json:async()=>data}}};
context.location=context.window.location;vm.createContext(context);vm.runInContext(script,context);
(async()=>{
 await vm.runInContext('boot()',context);
 assert.equal(els.physical.value,'UNKNOWN');assert.equal(els.modernization.value,'ORIGINAL');assert.equal(els.fit.value,'TARGET');assert.equal(els.reason.value,draft.reason);
 assert.equal(calls.filter(c=>c.method==='POST').length,0,'Opening a draft cannot spend or save');
 assert.equal(els['draft-status'].textContent,'AI draft ready for your review');assert.equal(els.remarks.children[1].tag,'mark');
 await vm.runInContext('refreshDraft()',context);assert.equal(els.reason.value,draft.reason);
 reject=true;await assert.rejects(vm.runInContext('saveNext({preventDefault(){}})',context),/Evidence changed/);assert.equal(saved.length,0);assert.equal(els.reason.value,draft.reason);reject=false;
 vm.runInContext('state.dirty=false',context);detail.property.review={revision:3,status:'approved',physical_condition:'C3_WELL_MAINTAINED',modernization_state:'UPDATED',target_fit:'not_target',reason:'Human truth',reason_tags:['keep'],standout_image_ids:['photo']};
 await vm.runInContext("loadProperty('sample')",context);assert.equal(els.reason.value,'Human truth');assert.equal(els.fit.value,'NOT_TARGET');assert.equal(els['draft-status'].textContent,'Your saved review is loaded');assert.equal(vm.runInContext('state.dirty',context),false);
 els.reason.value='Human correction';await vm.runInContext('saveNext({preventDefault(){}})',context);assert.equal(saved.length,1);assert.equal(saved[0].expected_revision,3);assert.equal(saved[0].label_evidence_id,detail.label_evidence_id);assert.deepEqual(saved[0].reason_tags,['keep']);assert.deepEqual(saved[0].standout_image_ids,['photo']);assert.equal(saved[0].status,'approved');
 assert(!calls.some(c=>/train|freeze|infer|propose/.test(c.path)),'No inference, training, freeze or paid requests');console.log('PASS: auto draft, highlighted quotes, no paid calls, saved-human preservation, stale-save retention, CAS and Advanced provenance');
})().catch(e=>{console.error(e);process.exitCode=1});
